package demo.demoproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Produto implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Nome do Produto")
   private java.lang.String nome;
   @org.kie.api.definition.type.Label(value = "Vers\u00E3o")
   private java.lang.Integer versao;

   public Produto()
   {
   }

   public java.lang.String getNome()
   {
      return this.nome;
   }

   public void setNome(java.lang.String nome)
   {
      this.nome = nome;
   }

   public java.lang.Integer getVersao()
   {
      return this.versao;
   }

   public void setVersao(java.lang.Integer versao)
   {
      this.versao = versao;
   }

   public Produto(java.lang.String nome, java.lang.Integer versao)
   {
      this.nome = nome;
      this.versao = versao;
   }

}